<?php

return [

    'order_statuses' => [
        'Abandoned' => 'Abandoned',
        'On Hold' => 'On Hold',
        'Pending supplier' => 'Pending supplier',
        'Pending customer' => 'Pending customer',
        'Confirmed' => 'Confirmed',
        'Cancelled' => 'Cancelled',
        'Abandoned cart' => 'Abandoned cart',
    ],

    'status_with_code' => [
            1 => 'Abandoned',
            2 => 'On Hold',
            3 => 'Pending supplier',
            4 => 'Pending customer',
            5 => 'Confirmed',
            6 => 'Cancelled',
            7 => 'Abandoned cart',
    ],
    'currencies' => [
        'USD' => 'United States – USD',
        'AED' => 'United Arab Emirates – AED',
        'AFN' => 'Afghanistan – AFN',
        'ALL' => 'Albania – ALL',
        'AMD' => 'Armenia – AMD',
        'ANG' => 'Netherlands Antilles – ANG',
        'AOA' => 'Angola – AOA',
        'ARS' => 'Argentina – ARS',
        'AUD' => 'Australia – AUD',
        'BDT' => 'Bangladesh – BDT',
        'CAD' => 'Canada – CAD',
        'CHF' => 'Switzerland – CHF',
        'CNY' => 'China – CNY',
        'DKK' => 'Denmark – DKK',
        'EGP' => 'Egypt – EGP',
        'EUR' => 'Eurozone – EUR',
        'GBP' => 'United Kingdom – GBP',
        'HKD' => 'Hong Kong – HKD',
        'IDR' => 'Indonesia – IDR',
        'ILS' => 'Israel – ILS',
        'INR' => 'India – INR',
        'JPY' => 'Japan – JPY',
        'KRW' => 'South Korea – KRW',
        'MXN' => 'Mexico – MXN',
        'MYR' => 'Malaysia – MYR',
        'NOK' => 'Norway – NOK',
        'NZD' => 'New Zealand – NZD',
        'PKR' => 'Pakistan – PKR',
        'PLN' => 'Poland – PLN',
        'QAR' => 'Qatar – QAR',
        'RUB' => 'Russia – RUB',
        'SAR' => 'Saudi Arabia – SAR',
        'SEK' => 'Sweden – SEK',
        'SGD' => 'Singapore – SGD',
        'THB' => 'Thailand – THB',
        'TRY' => 'Turkey – TRY',
        'ZAR' => 'South Africa – ZAR',
    ],

];
