<?php

return [

    'order_statuses' => [
        'Abandoned' => 'Abandoned',
        'On Hold' => 'On Hold',
        'Pending supplier' => 'Pending supplier',
        'Pending customer' => 'Pending customer',
        'Confirmed' => 'Confirmed',
        'Cancelled' => 'Cancelled',
        'Requires capture' => 'Requires capture',
        'Trip completed' => 'Trip completed',
    ],

    'status_with_code' => [
            1 => 'Abandoned',
            2 => 'On Hold',
            3 => 'Pending supplier',
            4 => 'Pending customer',
            5 => 'Confirmed',
            6 => 'Cancelled',
            7 => "Requires capture",
            8 => "Trip completed",
    ],
    'currencies' => [
        'USD' => 'United States – USD',
        'AED' => 'United Arab Emirates – AED',
        'AFN' => 'Afghanistan – AFN',
        'ALL' => 'Albania – ALL',
        'AMD' => 'Armenia – AMD',
        'ANG' => 'Netherlands Antilles – ANG',
        'AOA' => 'Angola – AOA',
        'ARS' => 'Argentina – ARS',
        'AUD' => 'Australia – AUD',
        'BDT' => 'Bangladesh – BDT',
        'CAD' => 'Canada – CAD',
        'CHF' => 'Switzerland – CHF',
        'CNY' => 'China – CNY',
        'DKK' => 'Denmark – DKK',
        'EGP' => 'Egypt – EGP',
        'EUR' => 'Eurozone – EUR',
        'GBP' => 'United Kingdom – GBP',
        'HKD' => 'Hong Kong – HKD',
        'IDR' => 'Indonesia – IDR',
        'ILS' => 'Israel – ILS',
        'INR' => 'India – INR',
        'JPY' => 'Japan – JPY',
        'KRW' => 'South Korea – KRW',
        'MXN' => 'Mexico – MXN',
        'MYR' => 'Malaysia – MYR',
        'NOK' => 'Norway – NOK',
        'NZD' => 'New Zealand – NZD',
        'PKR' => 'Pakistan – PKR',
        'PLN' => 'Poland – PLN',
        'QAR' => 'Qatar – QAR',
        'RUB' => 'Russia – RUB',
        'SAR' => 'Saudi Arabia – SAR',
        'SEK' => 'Sweden – SEK',
        'SGD' => 'Singapore – SGD',
        'THB' => 'Thailand – THB',
        'TRY' => 'Turkey – TRY',
        'ZAR' => 'South Africa – ZAR',
    ],
    'currency_symbols' => [
        'USD' => '$',
        'AED' => 'د.إ',
        'AFN' => '؋',
        'ALL' => 'L',
        'AMD' => '֏',
        'ANG' => 'ƒ',
        'AOA' => 'Kz',
        'ARS' => '$',
        'AUD' => 'A$',
        'BDT' => '৳',
        'CAD' => 'C$',
        'CHF' => 'CHF',
        'CNY' => '¥',
        'DKK' => 'kr',
        'EGP' => '£',
        'EUR' => '€',
        'GBP' => '£',
        'HKD' => 'HK$',
        'IDR' => 'Rp',
        'ILS' => '₪',
        'INR' => '₹',
        'JPY' => '¥',
        'KRW' => '₩',
        'MXN' => '$',
        'MYR' => 'RM',
        'NOK' => 'kr',
        'NZD' => 'NZ$',
        'PKR' => '₨',
        'PLN' => 'zł',
        'QAR' => 'ر.ق',
        'RUB' => '₽',
        'SAR' => '﷼',
        'SEK' => 'kr',
        'SGD' => 'S$',
        'THB' => '฿',
        'TRY' => '₺',
        'ZAR' => 'R',
    ],

    'stages' => [

        'cart' => [
            'entry',
            'validation',
            'order_created',
            'calculation_done',
            'completed',
        ],

        'customer' => [
            'start',
            'saved',
        ],

        'promo' => [
            'start',
            'validated',
            'applied',
        ],

        'payment' => [
            'stripe_init',
            'pi_detect',
            'pi_create',
            'pi_created',
            'deposit_mode',
            'success',
            'failed',
        ],

        'email' => [
            'start',
            'template_loaded',
            'customer_loaded',
            'tour_loaded',
            'summary_built',
            'mail_sending',
            'mail_sent',
            'history_saved',
        ],

        'mail' => [
            'start',
            'sent',
            'failed',
        ]

    ],

    // Order flow sequence (VERY IMPORTANT)
    'flow' => [
        'cart',
        'customer',
        'promo',
        'payment',
        'email',
    ],



];
